### ISSUE TITLE
Change and increase font size across application

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

the font and font size is sterile and hard to read at times

### Describe the solution you'd like

increase font size and change font type

**Comment by lyndsayhawkins** [comment]
are there font choices that I can look it to chose from?

**Comment by AndrewBabbitt97** [comment]
Fonts are based on your operating system, as such it varies based on Mac, Windows, Android, and Linux. We use the standard accessable UI font for each OS. This is determined by Primer.

We can increase font sizes in areas but we have to know the biggest trouble areas to do so.
