### ISSUE TITLE
delete applications

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

cannot delete applications

### Describe the solution you'd like

need to be able to delete applications

**Comment by lyndsayhawkins** [comment]
@AndrewBabbitt97  when i was going through everything I think this issue is the same as issue #54 - do you want to merge them?

**Comment by AndrewBabbitt97** [comment]
Closing in favor of #54
