### ISSUE TITLE
add search bar to search by last name 

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

search bar doesn't work currently

### Describe the solution you'd like

add a search bar to be able to search by candidate last name

**Comment by AndrewBabbitt97** [comment]
Look at why search is inconsistent

**Comment by AndrewBabbitt97** [comment]
We probably also need some indexes on many fields in the database, we search A LOT of stuff on the grids including resume text. This can make searches take 40+ seconds. So this may also be why people think search isnt working @lyndsayhawkins
