### ISSUE TITLE
Sort candidates by prescreen activity 

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

There is no way for us to isolate which candidates have been prescreened specifically.

### Describe the solution you'd like

We'd like to be able to isolate all candidates who have been prescreened (meaning they have a prescreen activity logged in their candidate record).

**Comment by keithlogan94** [comment]
Don't include
less 50 charachters 
before may 12th 2023
