### ISSUE TITLE
BUG | Save button overlaps position title on a job record

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The save button overlaps the position title on a job record 

![Screenshot 2023-09-20 113710](https://github.com/recro/ats-issues/assets/135051191/87fd8d9e-d9fc-4714-a615-a889252d23b7)

**Comment by lyndsayhawkins** [comment]
@keithlogan94 that sounds good

**Comment by keithlogan94** [comment]
@Deadwing91 can you create a release?

**Comment by keithlogan94** [comment]
Later
