### ISSUE TITLE
Create activity when the application status is changed

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I cannot see the activity in an application when the status is changed

### Describe the solution you'd like

- I'd like the status change to show up in the activity feed in an application
-  {DATE} - {USER} - changed from {old state} to {new state} 
-  Also show the date of last state change on application grid

### Additional context

-

**Comment by AndrewBabbitt97** [comment]
Blocked by #18
