### ISSUE TITLE
FEATURE | Email Integration/Threads

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the emails are loading individually which makes it harder to read and keep track of

### Expected behavior

there should be an option to expand the email and view the thread

**Comment by lyndsayhawkins** [comment]
@keithlogan94

- duplicates still populating (example candidate Frank Valenzuela (image attached - looks like there are a few hundred duplicate emails loaded on this candidate's profile) 
- Another candidate we're seeing duplicates on recently is Aujanae Oliver.
![Screenshot 2023-10-30 141916](https://github.com/recro/ats-issues/assets/135051191/fa4ff773-3742-4ccb-a1b0-daff7a343444)

- add an expand/collapse function to threads so that they don't take up extract space in the feed.

**Comment by lyndsayhawkins** [comment]
@keithlogan94 being able to collapse threads is still a priority.

**Comment by keithlogan94** [comment]
combining into single ticket
