### ISSUE TITLE
FEATURE | Email Integration - Email Send/Reply Function

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

We are unable to send and reply to emails directly from the ATS. Recruiters currently go to gmail to send a new email and reply to a current thread when they should be able to do that out of the ATS.

### Describe the solution you'd like

- When the reply button is selected, the user should be able to reply directly to the email thread
- the user should be able to select "send new email" and a text box should appear where they can modify the subject, sender and body of the email 
- When replying or creating a new thread, the ATS should utilize the users saved signature from the email client OR the user can create a signature to be saved and used across both

**Comment by keithlogan94** [comment]
generate notification when candidate emails recruiter

**Comment by keithlogan94** [comment]
combining into single ticket
