### ISSUE TITLE
Dashboard - Create new table that calculates all emails being sent 

### ISSUE THREAD

**Issue by MalachiRecro** [recro/ats-issues#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

there is no way to capture how many emails are being sent overall

### Expected behavior

create separate table in the dashboard to reflect all emails being sent

**Comment by AndrewBabbitt97** [comment]
Added an aditional table listing all counts of activities:
![all](https://github.com/recro/ats-issues/assets/2308261/c8ed0654-8544-4317-9f73-d48093f9c291)
