### ISSUE TITLE
Change application grid tabs

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Applications are a fucking mess

### Describe the solution you'd like

Change tabs to be: My Open Applications, Open Applications, All Applications

My open applications: 
   filtered by owner to the current user:
   
    States that Show:
    - Open Applications Statuses: Active, prescreen, submitted, interview requested, interview scheduled, selected for hire, offer extended offer accepted, crossover started, crossover completed, briefing completed, hired

Open applications:
-   States that Show:
1.     Open Applications Statuses: Active, prescreen, submitted, interview requested, interview scheduled, selected for hire, offer extended, offer  accepted, crossover started, crossover completed, briefing completed, hired

All applications:
 - all open and closed applications 

=====================================
open applications statuses:
- Open Applications Statuses: Active, prescreen, submitted, interview requested, interview scheduled, selected for hire, offer accepted, crossover started, crossover completed, briefing completed, hired, started, 

closed applications statuses
- Closed Applications States: Not selected for interview, not selected for hire, offer rejected, crossover denied, briefing not completed, inactive, candidate withdrew, candidate unresponsive, started, 

### Additional context

-

**Comment by lyndsayhawkins** [comment]
I reopened this issue because we noticed an application stage was missing from "open application status" - i added offer extended to be included in what an "open application" means

**Comment by AndrewBabbitt97** [comment]
Completed, will go out with todays update.
