### ISSUE TITLE
Remove Duplicate applications 

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There are duplicate records for applications 

### Expected behavior

Remove duplicate records

**Comment by lyndsayhawkins** [comment]
@AndrewBabbitt97 are we able to make this as closed?

**Comment by AndrewBabbitt97** [comment]
@lyndsayhawkins leaving this open as the current solution is only a workaround and not ideal. I want this to be around for tracking.

**Comment by lyndsayhawkins** [comment]
@AndrewBabbitt97 still want this to be around?

**Comment by AndrewBabbitt97** [comment]
I'll close as it's something we will resolve in Medulla Core
