### ISSUE TITLE
Application Activities

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like to see all the activities associated with a candidate application reflected in the candidate record. 

Example - candidate application is moved to "submitted" --> Activity logged in candidate record that says application was moved to submitted.

Example -> prescreen is completed within the application --> prescreen is visible in the candidate record

Example -> loi is attached in the application ---> file is visible in the candidate profile

### Describe the solution you'd like

I would like to see all the activities associated with a candidate application reflected in the candidate record. 

### Additional context

-

**Comment by AndrewBabbitt97** [comment]
This is going to require more thought and consideration before we put it in place as it has the potential to affect dashboard statistics.

**Comment by AndrewBabbitt97** [comment]
Closing in favor of #56
