### ISSUE TITLE
Use TinyMCE for activity creation / editing

### ISSUE THREAD

**Issue by recro-lataille** [recro/ats-issues#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Activities need the ability to have formatting included to better reference the information. implement TinyMCE

### Describe the solution you'd like

Implement the same rich text editor as job listings when creating an activity

### Additional context

N/A

**Comment by keithlogan94** [comment]
Tiny mce

**Comment by recro-lataille** [comment]
@keithlogan94 also ensure the appropriate icon populates for each activity type

**Comment by AndrewBabbitt97** [comment]
> @keithlogan94 also ensure the appropriate icon populates for each activity type

This is to be handled in #23
