### ISSUE TITLE
Job Grid - add location field 

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I need to be able to see the location and the clearance requirement when in the job grid view and do not need to see the published column

### Describe the solution you'd like

Add location and clearance requirement as a column in the job grid

### Additional context

-

**Comment by AndrewBabbitt97** [comment]
The way we handle this may end up determined by what we do in #18
