### ISSUE TITLE
Gmail integration

### ISSUE THREAD

**Issue by recro-lataille** [recro/ats-issues#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Recruiters currently copy paste a candidates email. Then send and track previous conversations in there email. Additionally the first few emails sent are standard templates that could be sent automatically freeing time to focus on higher value tasks.

### Describe the solution you'd like

The ability to;

1. Send an email directly from inside medulla when on a candidate or application record
2. Utilize read receipts to know if the email was opened and mark the email as opened within the activities section
5. See all email communication with a candidate for threads started within medulla in the candidates activity page
6. See all email communication with a candidate for a thread created on the application page - within the application page
7. Single button to initiate the sending of the first email and scheduling of follow-ups based on x number of days passing
9. Create automatic scheduled follow-up emails with the canidate if a response is not received
10. Emails utilize templates that are populated based on the fields within the candidates record

### Additional context

initially import all emails from our team and associate them to the canidate with a matching email

**Comment by lyndsayhawkins** [comment]
@keithlogan94 

- show first 10 lines in an email and then have expand option

**Comment by keithlogan94** [comment]
combining into single ticket
