### ISSUE TITLE
Set prescreened after prescreen activity

### ISSUE THREAD

**Issue by MalachiRecro** [recro/ats-issues#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

If a candidate is prescreened automatically set prescreen field to true

### Describe the solution you'd like

Prescreened
-- If a pre-screen record exists - or is created -  automatically set value to true
-- add prescreened to the grid at the far right

### Additional context

Prescreened
-- If a pre-screen record exists - or is created -  automatically set value to true
-- add prescreened to the grid at the far right

**Comment by AndrewBabbitt97** [comment]
@MalachiRecro need some additional details:

There is no prescreen boolean/checkbox on application nor candidates currently. I'm assuming you want this added as well.

Should it be added:
- On the candidate record
- On the application record
- Both

After we know this, we need details on how this should be handled depending on the above.

**Comment by lyndsayhawkins** [comment]
closed this due to adding the 'prescreened' tab on the candidate grid
