### ISSUE TITLE
Data is lost when changing tabs on candidate record

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Unable to flip between activity tab and resume tab while inputting a prescreen. If writing a prescreen, then flip to the resume tab, then back to the activity tab it erases all prescreen notes.

### Describe the solution you'd like

I'd like to be able to flip between the resume and the activity tab without losing the data that has been inputted in the prescreen box.

**Comment by AndrewBabbitt97** [comment]
This is going to be a part of a larger refactor and will likely be tackled when Nathan joins the team in July.

For now our recommended workaround is to use multiple tabs, I know its not the best but its the simplest approach for now.
