### ISSUE TITLE
Application - Prescreen notes not carrying over. 

### ISSUE THREAD

**Issue by MalachiRecro** [recro/ats-issues#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When you do a prescreen under the candidate's application the notes do not carry over to the candidate's profile. 

### Expected behavior

When a prescreen is completed under a candidate's application it should carry over to the candidate's profile 

### Steps to reproduce

Go to an open application
click prescreen 
type notes
save 
go to candidate profile

**Comment by AndrewBabbitt97** [comment]
This is a duplicate of / covered under #13
