### ISSUE TITLE
Candidate Profile - Prescreen notes editable 

### ISSUE THREAD

**Issue by MalachiRecro** [recro/ats-issues#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When you complete a pre-screen you can not go back to the pre-screen and edit it 

### Describe the solution you'd like

After you complete a prescreen you should be able to click back into it and edit it without it creating a duplicate activity

**Comment by keithlogan94** [comment]
only edit what you created
