### ISSUE TITLE
Application Grid - Search candidate name 

### ISSUE THREAD

**Issue by MalachiRecro** [recro/ats-issues#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

When you click the candidate column you should be able to search by FULL name instead of having to scroll down and select them

### Describe the solution you'd like

When you click the candidate column you should be able to search by FULL name instead of having to scroll down and select them

**Comment by MalachiRecro** [comment]
@AndrewBabbitt97 Any luck on this?

**Comment by AndrewBabbitt97** [comment]
@MalachiRecro 

Hasn't been actively worked as it's lower priority, if this is high priority we can escalate it.

**Comment by MalachiRecro** [comment]
@AndrewBabbitt97 Okay, I changed it to high priority
