### ISSUE TITLE
Multi-Select - not working

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Multi-select is not working.

### Expected behavior

When hitting shift and trying to select a group of candidates, it's not working.

**Comment by AndrewBabbitt97** [comment]
This was a style issue, multi select did work but selecting and hovering didnt change the background color in light mode only.

Will be released in tonight's update.
