### ISSUE TITLE
Bulk Record Updates

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I have to individually change application status and would like to submit a request for bulk changes to be made. 

### Describe the solution you'd like

- all applications that are under the "Allspark" contract and are marked "active" ---> change to "inactive"
- all applications that are under the "Broadside" contract that are marked "active" ---> change to "inactive"
- all applications that are under the "GEOSPI" contract that are in "active" OR "prescreen" stage ---> change to "submitted for bid/proposal"
- all applications that are under the "grimlock" contract that are marked "active" ---> change to "inactive"
- all applications that are under the "internal" contract ---> change to "submitted for bid/proposal"
- all applications that are under the "novastar" contract ---> change to "submitted for bid/proposal"

**Comment by AndrewBabbitt97** [comment]
All records listed have been updated.
