### ISSUE TITLE
Jobs - Updated rates for Walla Walla contract

### ISSUE THREAD

**Issue by MalachiRecro** [recro/ats-issues#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Please update the existing walla walla rates with the rates in the attached spreadsheet 

### Describe the solution you'd like

Please update the existing walla walla rates with the rates in the attached spreadsheet 

### Additional context

[Walla Walla Rates.xlsx](https://github.com/recro/ats-issues/files/11839567/Walla.Walla.Rates.xlsx)

**Comment by AndrewBabbitt97** [comment]
Just updated
