### ISSUE TITLE
Candidate records, documents  - Delete Button 

### ISSUE THREAD

**Issue by MalachiRecro** [recro/ats-issues#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Would like the ability to delete records if needed for Jobs, Applications, and Candidates, and remove documents 

### Describe the solution you'd like

Should be able to click a button on a job post, candidate record, and Applicaiton to delete that record.
After clicking delete it should pop up with a confirmation asking if you are sure and you would have to click yes.

**Comment by lyndsayhawkins** [comment]
@keithlogan94 when the delete icon is selected next to a document, add a notification that confirms that the user does want to delete that document.
