### ISSUE TITLE
Dashboard - Applications in Progress order

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

The status 'briefing completed' is listed last in the dashboard table application in progress

### Describe the solution you'd like

'briefing completed' should fall between 'crossover completed' and 'hired' when looking at the list

**Comment by AndrewBabbitt97** [comment]
Fixed this mornming
