### ISSUE TITLE
Add Willing to work in Field to candidates

### ISSUE THREAD

**Issue by MalachiRecro** [recro/ats-issues#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Would like a field on the left side to put which states candidates are willing to work in

### Describe the solution you'd like

Add willing to work in -Mod
List of states
Automatically add candidate state when record is created

### Additional context

Add willing to work in -Mod
List of states
Automatically add candidate state when record is creat

**Comment by AndrewBabbitt97** [comment]
Relates to #5
