### ISSUE TITLE
Add Rates for TARPON contract 

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I would like the attached rates added for the TARPON contract 

### Describe the solution you'd like

Please add the rates highlighted in yellow

[Tarpon_Pricing_Recro_LeadLCAT.xlsx](https://github.com/recro/ats-issues/files/12051998/Tarpon_Pricing_Recro_LeadLCAT.xlsx)

**Comment by AndrewBabbitt97** [comment]
Added
