### ISSUE TITLE
Add user tagging and notification system

### ISSUE THREAD

**Issue by MalachiRecro** [recro/ats-issues#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Would like to be able to Tag recruiters in certain candidates as a note. And they will need to get notified either in the ATS or by email. 

### Describe the solution you'd like

- Add a way to tag recruiters 
- Example: @lyndsay check out this candidate
- the recruiter tagged should get notified via email or ATS

### Additional context

- Add a way to tag recruiters 
- Example: @lyndsay check out this candidate
- the recruiter tagged should get notified via email or ATS

**Comment by lyndsayhawkins** [comment]
@AndrewBabbitt97 

I'd like email notifications to be sent to the recruiters when the following actions happen in the ATS:

- any time a job record status changes to 'open'
- any time a job record status changes to 'closed'
- any time a job record status changes to 'on hold'
- any time a job record priority changes to 'critical' or 'high'
- any time a new job record is created

The notification via email should include the following information - 

- the change that was made 
- the job id AND title 

ex - '333 - system administrator was changed to closed'
