### ISSUE TITLE
Change visual of owner on a candidate record when "no owner" is selected in light mode 

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when "no owner" is selected on a candidate record, it is displayed in white text with a yellow bubble - very hard to read
<img width="212" alt="Screenshot 2023-07-17 201543" src="https://github.com/recro/ats-issues/assets/135051191/7e529b12-27e8-4428-9095-a1f638e07615">

**Comment by keithlogan94** [comment]
EntityPage.razor : ln 189
