### ISSUE TITLE
FEATURE | Add pipeline option to candidate records 

### ISSUE THREAD

**Issue by lyndsayhawkins** [recro/ats-issues#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Recruiters that are reviewing candidates need to be able to associate them to jobs for which they may be fit even though they do not have the information to ensure that they are a fit. 

I'd like to be able to add job reqs (associations) to a candidate record 

### Describe the solution you'd like

DATA

- [x]  Add a status of pipelined to the list of application statuses  should be before active in order on the list
- [x] Move Interview Completed to the position after Interview Scheduled 
- [x] Delete started from active application list

APPLICATIONS SECTION
- [x] Make sure that applications with the status "pipelined" **do not** show up on the  My Open Applications, Open Applications, All Applications
- [x] Add a tabs to the application page my "My Pipeline", "All Pipeline". These pages will only show the the applications with the status "pipelined"

CANDIDATE PROFILE
- [x] Replicate the applications sections 
- [x] the original application section should not include the "pipelined" status 
- [x] the Pipeline section should show only the applications that are in the "pipelined" status 
- [x] If you click on the + icon next to the pipline section title it will create and application with the status of pipelined 

JOB LISTING
- [x] Replicate the applications sections 
- [x] the original application section should not include the "pipelined" status 
- [x] the Pipeline section should show only the applications that are in the "pipelined" status 
- [x] for the pipeline section remove the date and in its place put owner of the candidate
- [x]  If you click on the + icon next to the pipline section title it will create and application with the status of pipelined

**Comment by keithlogan94** [comment]
Is this still needed? @lyndsayhawkins

**Comment by keithlogan94** [comment]
Just wondering because it's an old ticket.

**Comment by lyndsayhawkins** [comment]
@keithlogan94 yes i still consider this a high priority.
