### ISSUE TITLE
Candidate Record - Edit Fields

### ISSUE THREAD

**Issue by MalachiRecro** [recro/ats-issues#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

Be able to edit important candidate information more efficiently 

### Describe the solution you'd like

- Move city state up to top of edit, Make it so that buttons display current value once you select it 
- Add quick update feature: you click on a field in the “view candidate” a popup comes up you can edit and click save
- Make it so that when you go into a field the entry area (if applicable) is activated and your cursor is in it

### Additional context

- Add quick update feature: you click on a field in the “view candidate” a popup comes up you can edit and click save
- Make it so that when you go into a field the entry area (if applicable) is activated and your cursor is in it

**Comment by keithlogan94** [comment]
remove firstname lastname fields
The full name at the top will be editable when clicked

**Comment by keithlogan94** [comment]
first and last name separatly editable

**Comment by keithlogan94** [comment]
On dropdowns automatically open clearance, degrees and set filter as focussed

**Comment by keithlogan94** [comment]
Remove copy from everything but name and contact info

**Comment by keithlogan94** [comment]
more padding in contact info

**Comment by keithlogan94** [comment]
remove double headers in select menu
